name: Flyway DB Migration Pipeline

on:
  workflow_dispatch:

jobs:
  flyway-migration:
    runs-on: self-hosted

    steps:

    # =========================
    # 1. Checkout code
    # =========================
    - name: Checkout Repository
      uses: actions/checkout@v4


    # Step 2: Install Flyway ONCE (No database credentials go here)
    - name: Set up Official Flyway CLI
      uses: red-gate/setup-flyway@v3
      with:
          edition: community
          i-agree-to-the-eula: true
        
    - name: Flyway Schema Validation
      run: flyway validate "-configFiles=./flyway.conf" "-url=${{ secrets.SQL_SERVER_URL }}" "-user=${{ secrets.SQL_SERVER_USER }}" "-password=${{ secrets.SQL_SERVER_PASSWORD }}"

      # Step 4: Run the Migrate Command using standard command line
    - name: Execute Pending Migrations
      run: flyway migrate "-configFiles=./flyway.conf" "-url=${{ secrets.SQL_SERVER_URL }}" "-user=${{ secrets.SQL_SERVER_USER }}" "-password=${{ secrets.SQL_SERVER_PASSWORD }}"

  

    - name: Stop if validate failed
      if: failure() && steps.validate.outcome == 'failure'
      run: exit 1


    # =========================
    # 3. Flyway Migrate (Deploy)
    # =========================
    - name: Flyway Migrate
      id: migrate
      if: success()
      uses: red-gate/setup-flyway@v3
      with:
        edition: community
        i-agree-to-the-eula: true
        operation: migrate
        url: ${{ secrets.SQL_SERVER_URL }}
        user: ${{ secrets.SQL_SERVER_USER }}
        password: ${{ secrets.SQL_SERVER_PASSWORD }}


    - name: Stop if migration failed
      if: failure() && steps.migrate.outcome == 'failure'
      run: exit 1


     

